### ISSUE TITLE
Post on FB pages

### ISSUE THREAD

**Issue by eliafino** [Ishikashah2510/cppsecrets_articles#1]
Hi, thanks for your codes!

I'm going crazy to post into facebook pages.

This correctly click to "New Post":

`        self.browser.find_element_by_xpath("//div[2]/div/div[2]/div/div/div/div/div[2]/div/div").click()`

I have update post_class to:

`            post_class = 'gcieejh5 bn081pho humdl8nn izx4hr6d rq0escxv oo9gr5id t5a262vz o0t2es00 b1v8xokw datstx6m f530mmz5 lzcic4wl ecm0bbzt rz4wbd8a sj5x9vvc a8nywdso k4urcfbm o8yuz56k'`

but no way to have working code.  No text writed to post.

**Comment by Ishikashah2510** [comment]
the id changes everytime you refresh, so you would have to pass xpath to make sure it works correctly.  Also, you would have to replace the spaces in your post_class with '.' to make it work correctly. Kindly try these two methods

**Comment by eliafino** [comment]
`            post_class = post_class.replace(' ', '.')
            click_post = self.browser.find_element_by_class_name(post_class).click()
`
This your code replace spaces to dot, working correctly! But I can't insert text... I thik the problem is here:
```
            post_content = self.browser.find_element_by_class_name('notranslate._5rpu')
            post_content = self.browser.switch_to_active_element()
            post_content.send_keys(text_to_post)
```

Thanks for your time!!!

**Comment by Ishikashah2510** [comment]
It could be that the class differs for you. Open the group link in the browser where you want to post, click on the 'create post' button. Then inspect the page, and using 'select a element in the page to inspect it' option(upper left corner of the inspect area), click on the text box. and you can try finding the class from there

**Comment by eliafino** [comment]
`<div aria-describedby="placeholder-4p2pt" aria-label="Scrivi qualcosa a Pagina di XYZ..." class="notranslate _5rpu" contenteditable="true" role="textbox" spellcheck="true" tabindex="0" style="outline: none; user-select: text; white-space: pre-wrap; overflow-wrap: break-word;"><div data-contents="true"><div class="" data-block="true" data-editor="4p2pt" data-offset-key="3gmme-0-0"><div data-offset-key="3gmme-0-0" class="_1mf _1mj"><span data-offset-key="3gmme-0-0"><br data-text="true"></span></div></div></div></div>`

class="notranslate _5rpu" but no text inserted in post...

Thanks anyway my friend

**Comment by eliafino** [comment]
I try to investigate, now with pytest I see an error:

`E   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".gcieejh5.bn081pho.humdl8nn.izx4hr6d.rq0escxv.oo9gr5id.t5a262vz.o0t2es00.b1v8xokw.datstx6m.f530mmz5.lzcic4wl.ecm0bbzt.rz4wbd8a.sj5x9vvc.a8nywdso.k4urcfbm.o8yuz56k"}`

Thank you very much for your code!!!

**Comment by Ishikashah2510** [comment]
The class you are using is  : ".gcieejh5.bn081pho.humdl8nn.izx4hr6d.rq0escxv.oo9gr5id.t5a262vz.o0t2es00.b1v8xokw.datstx6m.f530mmz5.lzcic4wl.ecm0bbzt.rz4wbd8a.sj5x9vvc.a8nywdso.k4urcfbm.o8yuz56k"

This has a extra dot in the beginning, so I guess you left a space by mistake

**Comment by eliafino** [comment]
Sorry, no space at beginning...

`            click_post = self.browser.find_element_by_xpath("//div[2]/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div")
`
for now by_xpath working good without recompile source with BeautifulSoup

Now I try to adapting this into my code with Firefox and Geckodriver

Thank you very very very much my friend!

**Comment by Ishikashah2510** [comment]
Great! Best of Luck!
